#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
CREATE ROLE lumo_admin LOGIN PASSWORD '${LUMO_ADMIN_PASSWORD}'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS INHERIT;
CREATE ROLE lumo_app LOGIN PASSWORD '${LUMO_APP_PASSWORD}'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS INHERIT;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO lumo_admin;
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO lumo_app;
GRANT CREATE ON DATABASE ${POSTGRES_DB} TO lumo_admin;
GRANT USAGE, CREATE ON SCHEMA public TO lumo_admin;
REVOKE CREATE ON DATABASE ${POSTGRES_DB} FROM lumo_app;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM lumo_app;
EOSQL
